# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: MyPool

steps:
- task: Maven@3
  inputs:
     goals: package
     mavenPomFile: "pom.xml"
     publishJUnitResults: true
     
  
